language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - pip install scipy numpy matplotlib cython mpi4py neuronpy
  - python setup.py develop
script:
  - py.test --cov=hoc2swc tests/
after_success:
  - coveralls