language: python
cache: pip
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y rpm
  - curl -o nrn.rpm https://neuron.yale.edu/ftp/neuron/versions/v7.6/nrn-7.6.x86_64-linux.rpm
  - rpm --install nrn.rpm
install:
  - pip install -r requirements.txt 
  - python setup.py develop
script:
  - py.test --cov=hoc2swc tests/
after_success:
  - coveralls