TITLE Mod file for component: Component(id=hd__vhalflmin73 type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    SUFFIX hd__vhalflmin73
    USEION h WRITE ih VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE l_instances                       : parameter
    
    RANGE l_tau                             : exposure
    
    RANGE l_inf                             : exposure
    
    RANGE l_rateScale                       : exposure
    
    RANGE l_fcond                           : exposure
    RANGE l_timeCourse_TIME_SCALE           : parameter
    RANGE l_timeCourse_VOLT_SCALE           : parameter
    RANGE l_timeCourse_vhalfl               : parameter
    
    RANGE l_timeCourse_t                    : exposure
    RANGE l_steadyState_TIME_SCALE          : parameter
    RANGE l_steadyState_VOLT_SCALE          : parameter
    RANGE l_steadyState_vhalfl              : parameter
    
    RANGE l_steadyState_x                   : exposure
    RANGE l_q10Settings_q10Factor           : parameter
    RANGE l_q10Settings_experimentalTemp    : parameter
    RANGE l_q10Settings_TENDEGREES          : parameter
    
    RANGE l_q10Settings_q10                 : exposure
    RANGE l_timeCourse_V                    : derived variable
    RANGE l_timeCourse_Vhalfl               : derived variable
    RANGE l_steadyState_V                   : derived variable
    RANGE l_steadyState_Vhalfl              : derived variable
    RANGE l_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)
    l_instances = 1 
    l_timeCourse_TIME_SCALE = 1 (ms)
    l_timeCourse_VOLT_SCALE = 1 (mV)
    l_timeCourse_vhalfl = -73 
    l_steadyState_TIME_SCALE = 1 (ms)
    l_steadyState_VOLT_SCALE = 1 (mV)
    l_steadyState_vhalfl = -73 
    l_q10Settings_q10Factor = 4.5 
    l_q10Settings_experimentalTemp = 306.15 (K)
    l_q10Settings_TENDEGREES = 10 (K)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    eh (mV)
    ih (mA/cm2)
    
    
    l_timeCourse_V                         : derived variable
    
    l_timeCourse_Vhalfl                    : derived variable
    
    l_timeCourse_t (ms)                    : derived variable
    
    l_steadyState_V                        : derived variable
    
    l_steadyState_Vhalfl                   : derived variable
    
    l_steadyState_x                        : derived variable
    
    l_q10Settings_q10                      : derived variable
    
    l_rateScale                            : derived variable
    
    l_fcond                                : derived variable
    
    l_inf                                  : derived variable
    
    l_tauUnscaled (ms)                     : derived variable
    
    l_tau (ms)                             : derived variable
    
    conductanceScale                       : derived variable
    
    fopen0                                 : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    rate_l_q (/ms)
    
}

STATE {
    l_q  
    
}

INITIAL {
    eh = -30.0
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    l_q = l_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=hd__vhalflmin73 type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=hd__vhalflmin73 type=ionChannelHH), from gates; Component(id=l type=gateHHtauInf)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=l type=gateHHtauInf)]))
    fopen0 = l_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ih = gion * (v - eh)
    
}

DERIVATIVE states {
    rates()
    l_q' = rate_l_q 
    
}

PROCEDURE rates() {
    
    l_timeCourse_V = v /  l_timeCourse_VOLT_SCALE ? evaluable
    l_timeCourse_Vhalfl = l_timeCourse_vhalfl ? evaluable
    l_timeCourse_t = ((exp (0.033264 * ( l_timeCourse_V  - (-75))))/(0.011 * (1 + (exp (0.08316 * ( l_timeCourse_V  - (-75)))))) ) *  l_timeCourse_TIME_SCALE ? evaluable
    l_steadyState_V = v /  l_steadyState_VOLT_SCALE ? evaluable
    l_steadyState_Vhalfl = l_steadyState_vhalfl ? evaluable
    l_steadyState_x = 1/(1 + (exp (- ( l_steadyState_V -( l_steadyState_Vhalfl ))/ (-8) )) ) ? evaluable
    l_q10Settings_q10 = l_q10Settings_q10Factor ^((temperature -  l_q10Settings_experimentalTemp )/ l_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=l type=gateHHtauInf), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    l_rateScale = l_q10Settings_q10 ? path based, prefix = l_
    
    l_fcond = l_q ^ l_instances ? evaluable
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=l type=gateHHtauInf), from steadyState; Component(id=null type=hd__vhalflmin73_l_inf_inf)
    l_inf = l_steadyState_x ? path based, prefix = l_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=l type=gateHHtauInf), from timeCourse; Component(id=null type=hd__vhalflmin73_l_tau_tau)
    l_tauUnscaled = l_timeCourse_t ? path based, prefix = l_
    
    l_tau = l_tauUnscaled  /  l_rateScale ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    rate_l_q = ( l_inf  -  l_q ) /  l_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
}

